version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: polygon-validator/settings.js
    ports:
      - 17152:8984
    networks:
      - br-polygonvalidator

networks:
    br-polygonvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.143.0/24
