version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: stacksvault-validator/settings.js
    ports:
      - 17143:8984
    networks:
      - br-stacksvalidator

networks:
    br-stacksvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.142.0/24
