version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17173:8984
    networks:
      - br-tonvalidator
    build:
      args:
        ENV_FILE: composes/ton/.env
    environment:
      PROFILE: prod
      CHAIN: ton

networks:
    br-tonvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.150.0/24