version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17110:8984
    networks:
      - br-hecovalidator
    build:
      args:
        ENV_FILE: composes/heco/.env
    environment:
      PROFILE: prod
      CHAIN: heco

networks:
    br-hecovalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.139.0/24