version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: wemixvault-validator/settings.js
    ports:
      - 17193:8984
    networks:
      - br-wemixvalidator

networks:
    br-wemixvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.151.0/24
