version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17130:8984
    networks:
      - br-klaytnvalidator
    build:
      args:
        ENV_FILE: composes/klaytn/.env
    environment:
      PROFILE: prod
      CHAIN: klaytn

networks:
    br-klaytnvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.141.0/24