version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17090:8984
    networks:
      - br-orbitvalidator
    build:
      args:
        ENV_FILE: composes/orbit/.env
    environment:
      PROFILE: prod
      CHAIN: orbit

networks:
    br-orbitvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.155.0/24