version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17060:8984
    networks:
      - br-celovalidator
    build:
      args:
        ENV_FILE: composes/celo/.env
    environment:
      PROFILE: prod
      CHAIN: celo

networks:
    br-celovalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.135.0/24