version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: celovault-validator/settings.js
    ports:
      - 18985:8984
    networks:
      - br-celovalidator

networks:
    br-celovalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.135.0/24
