version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: tonvault-validator/settings.js
    ports:
      - 17173:8984
    networks:
      - br-tonvalidator

networks:
    br-tonvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.150.0/24
