version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 17143:8984
    networks:
      - br-stacksvalidator
    build:
      args:
        ENV_FILE: composes/stacks/.env
    environment:
      PROFILE: prod
      CHAIN: stacks

networks:
    br-stacksvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.142.0/24