version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: metadiumvault-validator/settings.js
    ports:
      - 17195:8984
    networks:
      - br-metadiumvalidator

networks:
    br-metadiumvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.152.0/24
