version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 18983:8984
    networks:
      - br-epicleague
    build:
      args:
        ENV_FILE: composes/epicleague/.env
    environment:
      PROFILE: prod
      CHAIN: epicleague
networks:
    br-epicleague:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.143.0/24
