version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    ports:
      - 18991:8984
    networks:
      - br-iconvalidator
    build:
      args:
        ENV_FILE: composes/icon/.env
    environment:
      PROFILE: prod
      CHAIN: icon

networks:
    br-iconvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.133.0/24
